#The Fibonacci number is generated by adding the previous two terms. 
#For example: below is list of Fibonacci numbers:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#Find the sum of the even-valued terms by considering the terms in Fibonacci sequence whose value do not exceed a given "n"

def Fibo(n):
    total = 0
    f1 = 0
    f2 = 1
    for i in range(n):
      while f2 < n:
          if f2%2 == 0:
              total += f2
          f1, f2 = f2, f1 + f2
      return(total)
